name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: self-hosted  # Indicar que se ejecutará en un corredor autoalojado
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "¡Hola! Gracias por abrir este issue. En breve te responderemos."
        pr-message: "¡Hola! Gracias por hacer esta pull request. En breve te responderemos."
