name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Run Docker container
      run: docker run -d -p 8080:8080 christian1328/formulario:5.0

