name: Saludos

on:
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Saludo a los usuarios
      run: echo "¡Hola! Gracias por abrir este issue. En breve te responderemos."
